services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
With Postgres database:
Update your render.yaml to provide the DATABASE_URL environment variable to connect to your database:

services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand:
      yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: quotes
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: quotes
    plan: free